### PR TITLE
Improved regex.

### PR DESCRIPTION
**Pull request by baizon**
I've added my improved regex.

### CODE REVIEW

**Comment by IsSuEat** [comment]
I still find it too restricting for what it is worth. For example. google any streamers name and try to open that link directly from google. check this 
https://www.google.at/search?q=twitch+links&ie=utf-8&oe=utf-8&gws_rd=cr&ei=0NvlVLPWOcHpUp2-gMgH#q=starladder+twitch
I cant get a rightclick here with that twitch regex.

**Comment by baizon** [comment]
It's working for me, http://i.imgur.com/lSCG51o.png

**Comment by baizon** [comment]
Yes, there is one stream there called http://www.twitch.tv/team/starladder. But this isn't a stream, its a "team site". That was the reason i think.

**Comment by IsSuEat** [comment]
Yup, i think i actually hit a wrong link ;)

**Pull request merged**
