### PR TITLE
SVG loading icon & closes #29

### LINKED ISSUE #29: Context menu entry "Open in Livestreamer"
I would like to have a feature like this so I don't need to have another extension in my addon bar and still be able to use it with just a right click.

EDIT: Wait, this is something that already exists... Why am I not seeing it?
EDIT2: Oh, I need to right click a link that contains a Twitch channel... Why can't I just be in the Twitch channel and just right click something random (that's not a link) and open the video in Livestreamer?

### PR DESCRIPTION
**Pull request by julianrichen**
Changelog:
* Loading icon has been changed from a gif to a svg animation, matches text color and looks sharper; also smaller then the gif.
* Context-menu change (closes #29)
    * Right-clicking page will use the current active tab url
    * Right-clicking a link will use the href's link

Sorry for not splitting these into two seperate commits, I forgot the fork my branch into a sub branch.

### CODE REVIEW

**Comment by IsSuEat** [comment]
Hi Julian!
This seems to not work right here, for example when I click on a youtube preview image, the addon tells me that it couldn't find a plugin. On the link on the other hand it works fine. 
See here: https://vid.me/YBJm

Also with my current (pretty dark) desktop theme, I can't see the loading animation.

Greets, Armin

**Comment by julianrichen** [comment]
I think that is because it is seeing the element clicked is an img and not a a[href]. I'll see if I can fix it.

I wonder if we can check for dark variant themes and change the svg's color based on that.

**Comment by julianrichen** [comment]
Commit 5a19d9e should fix the element issue, however, it seems impossible on special elements. For example any of the "Live" stream boxes on the homepage of [HitBox.tv](http://www.hitbox.tv/) will not work because the links are generated with JS...

As well I learned certain media on YouTube (for example Vevo music videos) can not be played with Livestreamer because it is encrypted, might be worth improving the error messages depending on what Livestreamer says.

Still looking into the dark varient issue.

**Comment by IsSuEat** [comment]
What I dont understand atm is: why does clicking the image with the current version work, but with your version it wont. 
It seems like the selectorContext is important how the node and data are passed. Specifying *  as selectorContext doesn't seem to do the trick either.

**Comment by julianrichen** [comment]
As I continue to work on the style issue I'll share my experience, maybe someone might find it interesting.

So the short answer is as of July 2nd, 2015 no method exist to test if the users' current theme or default system settings has a dark theme installed. It has been proposed in [this bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=990477) report but it seems nothing was done.

My first goal was to find a way to test if the content should be darker or lighter then the background. I did this by calculating [YIQ](https://en.wikipedia.org/wiki/YIQ), which made me create [a JS function](https://github.com/julianrichen/javascript-dynamic-contrast).

I figured the above would be harder then finding the browsers/panel background color, however, I was wrong... I tried in `data/js/globa.js` to calculate the panel background color BUT it returns transparent...
`data/js/global.js`
```
console.log(window.getComputedStyle(document.body, null).backgroundColor); // Returns transparent
```

Assuming it was set globally I tried the the browser window (XUL document) its self in `lib/main.js` once again it returns transparent.

`lib/main.js`
```js
var browserDocument = require("sdk/window/utils").getMostRecentBrowserWindow(),
    browserStyles   = browserDocument.content.getComputedStyle(browserDocument.content.document.body, null).backgroundColor,
    browserStyles2  = browserDocument.content.getDefaultComputedStyle(browserDocument.content.document.body, null).backgroundColor;
console.log(browserStyles); // Returns transparent
console.log(browserStyles2); // Returns transparent
```

As you can see I'm calculating the `computedStyle` over just `style` since `style` is the inline style set by the user, rather then system.

Not really sure what else to try. I wanted to get this to working so we could also change other styles in the panel like the border color. I see in the video above it's set to `#cccccc` when it would be better to have a darker color like `#111111`.

I'll keep experimenting, maybe parsing the systems `chrome://browser/content/browser.css` or `chrome://browser/content/browser.xul` will do the trick, not sure if this effects users themes.

**Pull request closed without merging**
